[package]
name = "shufl"
version = "0.0.0"
edition = "2024"
license = "MPL-2.0"
description = "Shuffle values into a vector then drain them when pushed or at your accord"

[dependencies]
heapless = "0.8.0"

[features]
alloc=[]